### ISSUE TITLE
Epic Fail when sending bug report

### ISSUE THREAD

**Issue by bersbersbers** [suever/dicomsort#32]
Title says it all, I guess. That's v2.1.9 on Windows 10.

Traceback (most recent call last):

  File "C:\Users\IEUser\dicomsort\gui\__init__.py", line 233, in Report

AttributeError: 'module' object has no attribute 'urlencode'

**Comment by suever** [comment]
Thanks for submitting this. I'm actually working on a fix which should improve the error logging. I'll post back here with the results of that.

**Comment by suever** [comment]
Just noting that I will be working on this this week as part of the 3.0 release (added this issue to the milestone)
